language: node_js

node_js:
  - "0.10"

addons:
  code_climate:
    repo_token: 0ec01270aca4350c14339ff9aba82763ca0a272cd88f5e2a03ac7e2811730d20

#install:
#  - npm install
#  - npm install -g mocha-lcov-reporter codeclimate-test-reporter

before_script:
  - "mysql -e 'create database test_surf;'"
  - npm run-script instrument

after_success:
  - cat lcov.info | ./node_modules/.bin/codeclimate


