language: node_js

node_js:
  - "0.10"

addons:
  code_climate:
    repo_token: af286f54970b30afee4ad46c8d6b407c02cea276d4da9da6012f4f4a5da2db7c

before_script:
  - "mysql -e 'create database test_apsi;'"

after_success:
  - npm run-script instrument
  - npm run-script travis
  - npm run-script codeclimate


