language: node_js

node_js:
  - "0.10"

install:
  # Install package dependencies
  - npm install
  # Additional npm stuff that needs to be global
  - npm install -g grunt-cli coffee-script

script: grunt travis

before_script:
  # Setup database to test
  - mysql -e "create database test_spiral;"
